### ISSUE TITLE
Scene fails to load

### ISSUE THREAD

**Issue by Zamrod** [manuelVo/foundryvtt-lichtgeschwindigkeit#10]
When I open a scene I created, even with all other modules disabled, the scene fails to load with the following errors:

panicked at 'called `Option::unwrap()` on a `None` value', src/raycasting/raycasting.rs:165:22

Stack:

Error
    at imports.wbg.__wbg_new_59cb74e423758ede (http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit.js:654:19)
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[113]:0x2c8b2
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[241]:0x2f384
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[128]:0x2d884
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[136]:0x2ddc2
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[181]:0x2ed11
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[173]:0x2eb9d
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[178]:0x2ec87
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[166]:0x2e9d2
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[28]:0x2839

imports.wbg.__wbg_error_4bb6c2a97407129a @ lichtgeschwindigkeit.js:666
raycasting.js:48 RuntimeError: Failed to render WebGL canvas: unreachable
    at lichtgeschwindigkeit_bg.wasm:0x2d8a0
    at lichtgeschwindigkeit_bg.wasm:0x2ddc2
    at lichtgeschwindigkeit_bg.wasm:0x2ed11
    at lichtgeschwindigkeit_bg.wasm:0x2eb9d
    at lichtgeschwindigkeit_bg.wasm:0x2ec87
    at lichtgeschwindigkeit_bg.wasm:0x2e9d2
    at lichtgeschwindigkeit_bg.wasm:0x2839
    at computePolygon (lichtgeschwindigkeit_bg.wasm:0x23074)
    at Module.computePolygon (lichtgeschwindigkeit.js:293)
    at WallsLayer.wasmComputePolygon (raycasting.js:45)
wasmComputePolygon @ raycasting.js:48
raycasting.js:49 Data to reproduce the error (please always include this in bug reports!):
wasmComputePolygon @ raycasting.js:49
raycasting.js:71 <~!-m4G<ZuCG5nMj@P"J%j&c@.d6BE_EU^dM?JSHY?5u`@b$;+KjhNbNnm?JTQ90a[R-j5p7U9_)!WiEA<h0JnB]UeA$p1Ea[bj:hPR11<%:VG(_qUK^=(cd=iVuHF%;V(4?7a;k!V/Kk`KJYg!R/Nis1Rbe?d92D'^+?Pg/M#o]M\[PK.SH9lB'Aqp$YI]*)0>;j@eMGlF/)qcbh]SmSof.1Di/GqW2tV%_c,O`gi<YV2$Pc;6YFK-NAJ0gZK0SEODi40bMB_=2Q0*>;_Qe,l=X^G<F<#m,7W4:T,k=/>XX?ojumJIGE^:ji-rJ^rmT`=ee`'9H)Fif0r'1&$Y;JI@c[Ian>WgJ4k^Cr*S6hO`HK1dO0N?=\UY/E1M1B7IF6nMaH@K<=7`UM`'+"k\5,3Tg=i42j#`>WnBZ@rfo)!eG^$",EaI3N_#a4*\$$FB-;VEB(8"Iq!t8pGpIskm]Z7ss[c#0lo"2Tf`WKS`GdDqonXa!@`%,nD@cmT4Qo6#H?cS+/!!]`h)>A\:3bFgp4O6\CK,pCn)+-FFfpOSY-(M.rFa%MJ<aT/qN6sc*(NMgU]m[Q6f\q9->^/<llW+MSCRU/KRC3"NdUu#*HDPpIeK6JC,6ie3!CkCeiMEr'nCYQNCem>-n%ENla<`Ndk!HP^,+.DrIT81aFEKKYc?0uPV9qnNLNJdhnQl";HQ+beH2#n$_*!od>hJuK-LEt8>mB3_m(dQnpYIM"Nmb7aAdH/bN1Kscfbj"pg`rQBDjh^ggUAQF$*p*t@csMVrTC2CUSFm\O)^'i?+$^fUgr:Z`s=<T8f`lZ/Nrt%iI@:,7Z[!V1dL;]~>
rustifyParams @ raycasting.js:71
foundry.js:4422 RuntimeError: Failed to render WebGL canvas: unreachable
    at lichtgeschwindigkeit_bg.wasm:0x2d8a0
    at lichtgeschwindigkeit_bg.wasm:0x2ddc2
    at lichtgeschwindigkeit_bg.wasm:0x2ed11
    at lichtgeschwindigkeit_bg.wasm:0x2eb9d
    at lichtgeschwindigkeit_bg.wasm:0x2ec87
    at lichtgeschwindigkeit_bg.wasm:0x2e9d2
    at lichtgeschwindigkeit_bg.wasm:0x2839
    at computePolygon (lichtgeschwindigkeit_bg.wasm:0x23074)
    at Module.computePolygon (lichtgeschwindigkeit.js:293)
    at WallsLayer.wasmComputePolygon (raycasting.js:45)
initializeCanvas @ foundry.js:4422
lichtgeschwindigkeit.js:666 panicked at 'called `Option::unwrap()` on a `None` value', src/raycasting/raycasting.rs:165:22

Stack:

Error
    at imports.wbg.__wbg_new_59cb74e423758ede (http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit.js:654:19)
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[113]:0x2c8b2
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[241]:0x2f384
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[128]:0x2d884
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[136]:0x2ddc2
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[181]:0x2ed11
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[173]:0x2eb9d
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[178]:0x2ec87
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[166]:0x2e9d2
    at http://zamrod.asuscomm.com:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[28]:0x2839

imports.wbg.__wbg_error_4bb6c2a97407129a @ lichtgeschwindigkeit.js:666
raycasting.js:48 RuntimeError: unreachable
    at lichtgeschwindigkeit_bg.wasm:0x2d8a2
    at lichtgeschwindigkeit_bg.wasm:0x2ddc2
    at lichtgeschwindigkeit_bg.wasm:0x2ed11
    at lichtgeschwindigkeit_bg.wasm:0x2eb9d
    at lichtgeschwindigkeit_bg.wasm:0x2ec87
    at lichtgeschwindigkeit_bg.wasm:0x2e9d2
    at lichtgeschwindigkeit_bg.wasm:0x2839
    at computePolygon (lichtgeschwindigkeit_bg.wasm:0x23074)
    at Module.computePolygon (lichtgeschwindigkeit.js:293)
    at WallsLayer.wasmComputePolygon (raycasting.js:45)
wasmComputePolygon @ raycasting.js:48
raycasting.js:49 Data to reproduce the error (please always include this in bug reports!):
wasmComputePolygon @ raycasting.js:49
raycasting.js:71 <~!-m4G<ZuCG5nMj@P"J%j&c@.d6BE_EU^dM?JSHY?5u`@b$;+KjhNbNnm?JTQ90a[R-j5p7U9_)!WiEA<h0JnB]UeA$p1Ea[bj:hPR11<%:VG(_qUK^=(cd=iVuHF%;V(4?7a;k!V/Kk`KJYg!R/Nis1Rbe?d92D'^+?Pg/M#o]M\[PK.SH9lB'Aqp$YI]*)0>;j@eMGlF/)qcbh]SmSof.1Di/GqW2tV%_c,O`gi<YV2$Pc;6YFK-NAJ0gZK0SEODi40bMB_=2Q0*>;_Qe,l=X^G<F<#m,7W4:T,k=/>XX?ojumJIGE^:ji-rJ^rmT`=ee`'9H)Fif0r'1&$Y;JI@c[Ian>WgJ4k^Cr*S6hO`HK1dO0N?=\UY/E1M1B7IF6nMaH@K<=7`UM`'+"k\5,3Tg=i42j#`>WnBZ@rfo)!eG^$",EaI3N_#a4*\$$FB-;VEB(8"Iq!t8pGpIskm]Z7ss[c#0lo"2Tf`WKS`GdDqonXa!@`%,nD@cmT4Qo6#H?cS+/!!]`h)>A\:3bFgp4O6\CK,pCn)+-FFfpOSY-(M.rFa%MJ<aT/qN6sc*(NMgU]m[Q6f\q9->^/<llW+MSCRU/KRC3"NdUu#*HDPpIeK6JC,6ie3!CkCeiMEr'nCYQNCem>-n%ENla<`Ndk!HP^,+.DrIT81aFEKKYc?0uPV9qnNLNJdhnQl";HQ+beH2#n$_*!od>hJuK-LEt8>mB3_m(dQnpYIM"Nmb7aAdH/bN1Kscfbj"pg`rQBDjh^ggUAQF$*p*t@csMVrTC2CUSFm\O)^'i?+$^fUgr:Z`s=<T8f`lZ/Nrt%iI@:,7Z[!V1dL;]~>
rustifyParams @ raycasting.js:71
lichtgeschwindigkeit_bg.wasm:0x2d8a2 Uncaught (in promise) RuntimeError: unreachable
    at lichtgeschwindigkeit_bg.wasm:0x2d8a2
    at lichtgeschwindigkeit_bg.wasm:0x2ddc2
    at lichtgeschwindigkeit_bg.wasm:0x2ed11
    at lichtgeschwindigkeit_bg.wasm:0x2eb9d
    at lichtgeschwindigkeit_bg.wasm:0x2ec87
    at lichtgeschwindigkeit_bg.wasm:0x2e9d2
    at lichtgeschwindigkeit_bg.wasm:0x2839
    at computePolygon (lichtgeschwindigkeit_bg.wasm:0x23074)
    at Module.computePolygon (lichtgeschwindigkeit.js:293)
    at WallsLayer.wasmComputePolygon (raycasting.js:45)

**Comment by manuelVo** [comment]
Thanks for the report!
