### ISSUE TITLE
"canvas drawing failed for lighting layer" error on excessively large map

### ISSUE THREAD

**Issue by Cubius** [manuelVo/foundryvtt-lichtgeschwindigkeit#19]
I have an enormous map in my game, pushing the limits of what my browser can render as a single image and since it is an old school dungeon map there are just _**a lot**_ of walls. Was hoping the map would run a little better with this module but at the moment it's not running at all, though that is to be expected since this is already pushing the regular lighting to its limits.

Below the error info from the console.

[lichterror.txt](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/6779153/lichterror.txt)

**Comment by manuelVo** [comment]
Wow, that's truly a huge map. The light source (or possibly token) that's portrayed as token on this image is the light source that is preventing the map from loading. It would be great if you could do the following:
- Remove all the walls except the pillar that the token is standing on and see if the error still occurs
- If the error no longer occurs please try to reduce the number of walls as much as possible such that the error still occurs (lines outside of the line of sight of the offending light can probably be deleted without changing anything)

If you can send me the error data for a scene with tokens removed in this manner that would help me a great deal in pinpointing and fixing this bug.

**Comment by manuelVo** [comment]
I've managed to reduce the issue down to a set of 3 walls.
```
<~!dNFYNOoLI:^fc;DZ_M,>epm1mN`(T"5UiuXK6eQ#s*an3eA=G9.WsH#/\K5RtQS+qLn:R1,7NS\T`2$59h18F?XcR-+aaba3PbbW!lq+DZ'>%(38AGlaR:7"QGi,d0U9#-\M~>
```

**Comment by Cubius** [comment]
> I've managed to reduce the issue down to a set of 3 walls.
> 
> ```
> <~!dNFYNOoLI:^fc;DZ_M,>epm1mN`(T"5UiuXK6eQ#s*an3eA=G9.WsH#/\K5RtQS+qLn:R1,7NS\T`2$59h18F?XcR-+aaba3PbbW!lq+DZ'>%(38AGlaR:7"QGi,d0U9#-\M~>
> ```

I'm not too well versed with Foundry's inner workings, how would I find these walls on the map? Or can I just delete them via the console?


>     * Remove all the walls except the pillar that the token is standing on and see if the error still occurs

There's a lot of tokens on the map, I populated it since base Foundry can handle it. I'll try making a backup and start sweepingly deleting tokens.


>     * If the error no longer occurs please try to reduce the number of walls as much as possible such that the error still occurs (lines outside of the line of sight of the offending light can probably be deleted without changing anything)

As far as the number of walls goes I've already kept it as low as I could for the most part, only having some excess walls on some round sections of the map.

Edit: Error w/out tokens, at a glance almost identical except for the last bits of it [lichterrornotokens.txt](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/6783938/lichterrornotokens.txt)

**Comment by manuelVo** [comment]
With the help of the reduced set of walls I've posted above I was able to fix the issue. I'll release a new version that'll fix the bug that's contained within the debug information you posted soon.

**Comment by Cubius** [comment]
That's great to hear, thanks so much and I'll be looking forward to the next version!
