### ISSUE TITLE
Background map dissapears for a frame when moving a token on a small map

### ISSUE THREAD

**Issue by MAClavell** [manuelVo/foundryvtt-lichtgeschwindigkeit#21]
FoundryVTT version: 0.8.8
System: DnD5e 1.3.6
Lichtgeschwindigkeit version: 1.3.4

With only Lichtgeschwindigkeit enabled I noticed the background map disappearing at various points when moving a token. 

Some info:
- I could only produce this bug on a small map with few walls. A large map with a ton of walls did not have this issue occurring.
- It still occurs when I delete every wall and refresh Foundry.
- There was no error printed to the console.

Here's the world with a copy of the map:
[lich-testing.zip](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/6813253/lich-testing.zip)

Here's a video (had to .zip it because the file was too large):
[Disappearing-Canvas.zip](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/6813273/Disappearing-Canvas.zip)

![IssueFreezeFrame](https://user-images.githubusercontent.com/25129246/125554374-625f5e08-9a7f-4dfb-8eb0-1ca32bdad9b4.jpg)

**Comment by manuelVo** [comment]
I'm unable to reproduce this using your test world. Have you verified that this isn't happening with Lichtgeschwindigkeit disabled, to rule out the possibility of a bug in Foundry core?

**Comment by MAClavell** [comment]
Yep, this doesn't happen with Lichtgeschwindigkeit disabled.

**Comment by manuelVo** [comment]
Does it still happen if you disable fog exploration on that map?

**Comment by MAClavell** [comment]
It does not happen with fog exploration disabled.

**Comment by manuelVo** [comment]
Thanks, I've managed to reproduce this on my machine.

**Comment by manuelVo** [comment]
I think I may have fixed the bug. However I was only able to reproduce this so rarely, that I cannot really confirm if the fix is actually working. Can you test if the bug still occurs, if you install Lichtgeschwindigkeit form this manifest? https://raw.githubusercontent.com/manuelVo/foundryvtt-lichtgeschwindigkeit/fog-flicker-fix/module.json

**Comment by MAClavell** [comment]
Yep that seems to have fixed it :)
