### ISSUE TITLE
Better Roof incompatability

### ISSUE THREAD

**Issue by sebbosaurus** [manuelVo/foundryvtt-lichtgeschwindigkeit#23]
When I use this module alongside my scenes with Better Roofs, the roofs are only visible from certain angles. When I move a token around the roof, it will appear properly only when the token is to the left or below the roof. When the token is positioned above the roof or to the right, it appears blacked out (as if visiblity was being blocked). I've tried removing lichgeschwindigkeit and the problem is fixed.

Let me know if I can provide any more information. Thank you!

**Comment by manuelVo** [comment]
I've been in contact with the author of better roofs and this is an issue that will need to be fixed in better roofs. I'll leave this issue open until the issue has been resolved on their side.

**Comment by theripper93** [comment]
this has been solved
