### ISSUE TITLE
Limited sight angle/light emission angle bug

### ISSUE THREAD

**Issue by BlackMoons** [manuelVo/foundryvtt-lichtgeschwindigkeit#25]
Hello, I have player with the following settings:
Dim vision: 0
Bright vision: 0
Sight angle: 160
Dim light radius 20
Bright Light Radius 10
Emission angle 240
Light animation type: torch
color: #ffbb33, intensity 0.5

When I rotate his icon 180 degrees around (ctrl + mousewheel), most of his emitted light disappears. If he moves left/right, the light randomly grows/shrinks between full and a tiny sliver. 

Steps to reproduce:
Be on a large map (2000x2000 pixels or more)
Be near the bottom/center of the map (Bug appears to not occur when you go to the top of the map, seems to not occur near left edge either)
Rotate 180 degrees around with ctrl+mousewheel or shift+mousewheel

![image](https://user-images.githubusercontent.com/15382398/131719325-40de8ede-c0d4-4768-8260-99ae672f7146.png)
![image](https://user-images.githubusercontent.com/15382398/131719375-45f8abc3-7c6a-4afd-9169-ca0755e97bd0.png)

Shows what it should look like, and does when token is not 180 degrees rotated:
![image](https://user-images.githubusercontent.com/15382398/131719485-ed6c3f0b-fc2d-4c15-ba47-03930366f1f9.png)

**Comment by manuelVo** [comment]
Please do the following:
- Open up the JavaScript console (you can open it by pressing F12)
- Enter `CONFIG.debug.sightRays = true;` into the console and press enter
- Move the token into a position so that the bug occurs
- Post the text that has been printed into the console (the last of the texts is enough) here. It contains valuable debug data that helps me reproducing the bug

**Comment by BlackMoons** [comment]
K it returned this:
[light error.txt](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/7093449/light.error.txt)

Also iv found the bug does occur sometimes when at one ctrl+mousewheel notch off 180 degrees, but 180 degrees it seems worse and one shift+mousewheel rotation makes me unable to trigger the bug.

**Comment by BlackMoons** [comment]
PS: Not sure if its any help, but while the debug lines where on, none of them 'moved' unexpectedly while the bug occurred.

**Comment by manuelVo** [comment]
Thanks. I was able to reproduce this using the data you sent me.

For future reference:
```
<~"*iOZNkYod:_^pqQ-ml$*l2GO:SX/=?(pVJ174:gNQ%[J`F/9"3ppr%c>\5\Vsc_1!.^)`#A7K1?G(Ea$So_^SoGo],<fp'>/+O(9kq9='iU`PNsSI;TfkIHG0?,;gm@Vg<Xi>GPkBnLc!t4E$YhaKastI~>
```

**Comment by BlackMoons** [comment]
Glad to hear it was reproducible. Sorry for the file dump of excess info. Didn't know exactly what you wanted and didn't trust github not to helpfully remove certain characters so I decided a file was the best way.

**Comment by manuelVo** [comment]
That's alright. Pulling the necessary info out of that file was simple enough.
