### ISSUE TITLE
open close doors do not update Light sight...

### ISSUE THREAD

**Issue by jacksands** [manuelVo/foundryvtt-lichtgeschwindigkeit#26]
if a door is opened or closed the sight is only updated after some token movement, I believe it is some other module incompatibility, but havent been able to find anything, even disabling all modules except ligthspeed do not solves it..

**Comment by manuelVo** [comment]
There's a module called "find the culprit" that'll help you figure out which module is responsible.

**Comment by jacksands** [comment]
Tks! it helped!   it was Less fog.... what a shame.. I liked it...
but like yours more!

**Comment by manuelVo** [comment]
Am I understanding you correctly, that lessfog doesn't work properly with Lichtgeschwindigkeit enabled?

**Comment by jacksands** [comment]
Less fog apply normally the reduced intensity of darkness, but for some reason when both modules are on open and closing doors do not update the vision...
like a token is at a closed door and can't see inside, when the door opens, even with light, the area remains dark until the token moves...  but if you close the same door before moving, it reveals the area... 

I will try make a video showing this for you

**Comment by jacksands** [comment]
NEWS!!
I Tried to make a video for you, and less fog just get an update and the problem disappeared!!!

**Comment by manuelVo** [comment]
Good to hear!
