### ISSUE TITLE
Error rendering when placing token in a specific spot

### ISSUE THREAD

**Issue by elemorelli** [manuelVo/foundryvtt-lichtgeschwindigkeit#28]
Hi!

We're having an error when a token is placed on or moved into a specific spot on a scene. I guess it's a really specific set of parameters that makes impossible to render the light/shadows. 

If a token is placed on the red square, the whole scene is unable to be reloaded until Lichtgeschwindigkeit is disabled.

https://imgur.com/aIcSGlT

This is the error logged into the browser's console:

https://gist.githubusercontent.com/elemorelli/cbb84c133c586e9a7a7521966d5cb708/raw/830448b189306f11963eb8e184b52ab117156c23/gistfile1.txt

These are our other active modules:
https://gist.githubusercontent.com/elemorelli/8b4d14b419132448ecd9d2fad00a9d04/raw/7c4c13b1539a924622a081e73b5333feaf4e80c2/gistfile1.txt

We were unable to find other spots with this error, but please, let me know if you need more info. 

Thanks in advance!

**Comment by manuelVo** [comment]
Thanks for the report! This turns out to be the exact same bug that was reported in #27 and will be fixed in the next release.
