### ISSUE TITLE
Light leak

### ISSUE THREAD

**Issue by ariakas2008** [manuelVo/foundryvtt-lichtgeschwindigkeit#29]
Hi, as you can see I have this strange light leak in one of my map:
![image](https://user-images.githubusercontent.com/49585869/134009101-62256b8e-9940-41d3-a7a4-14b0deed3abd.png)
This disappears if I disable lichtgeschwindigkeit.
My active modules list:
Active Modules:
----------
About Time v 1.0.4;
Actually Private Rolls v 0.2;
Ammo Tracker v 0.1.4;
Arbron’s Improved HP Bar v 2.1.0;
Babele v 2.0.6;
Better Rolls for 5e v 1.6.8;
Better Roofs v 0.9.9.3;
CodeMirror v 5.58.3-fvtt3;
Colored Folder Contents v 1.01;
Combat Utility Belt v 1.6.2;
Core Italian Translation v 0.24;
Crash's Automatic Blind Rolls (5e) v 0.8.1;
Custom Css v 2.1.0;
DF Quality of Life v 1.5.2;
DFreds Droppables v 1.2.10;
DF Settings Clarity v 3.2.1;
Dice So Nice! v 4.1.5;
Dice Tray v 1.2.1;
Disable Mouse Wheel Control for Sliders v 1.2.3;
DnD5e Italian Translation v 0.43;
DnD5e Plus v 1.1;
DnD5e Ui v 1.4.2;
Drag Ruler v 1.8.2;
Drag Upload (Get Over Here!) v 2.0.0;
Dynamic effects using Active Effects v 0.8.51;
Force Client Settings v 1.0.2;
FoundryVTT Arms Reach v 2.0.9;
FXMaster v 1.2.1;
GM Notes v 0.4.1;
Illandril's Inventory Sorter (5e) v 1.1.3;
Illandril's Token HUD scaler v 1.4.2;
Initiative Double Click v 1.2;
Item Containers v 1.8.5;
Item Delete Check v 1.1.4;
Laptop Form Fix v 0.0.8;
Lazy Money v 0.9.13;
Less Fog v 0.8.6;
Let's Trade 5e v 0.3.0;
Levels v 1.9.3;
lib - Color Settings v 2.8.0;
Library: DF Hotkeys v 2.3.5;
libWrapper v 1.10.6.0;
Loot Sheet NPC 5e v 3.1.0;
Maestro v 0.7.5;
Magic Items v 2.1.2;
Multilevel Tokens v 1.5.2;
Perfect Vision v 2.9.10;
Permission Viewer v 0.8.10;
Ping Logger v 1.2.10;
Pings v 1.2.12+0.8.6;
Polyglot v 1.7.18;
Search Anywhere v 2.2.0;
Settings Extender v 1.1.6+0.8.6;
Show Notes v 0.5;
Simple Calendar v v1.3.39;
Simple Dice Roller v 1.3.0;
Simplefog - Manual Fog of War v 0.1.18;
socketlib v 1.0.9;
Switch to Chat v 1.1.1;
Tidy5e Sheet v 0.5.16;
Tidy UI - Game Settings v 0.1.25;
Token Action HUD v 1.3.11;
Token Auras v 1.14;
Token HUD Wildcard v 1.4.0;
Token Magic FX v 0.5.2.1;
Track Tracker v 0.4.5;
Turn Marker v 2.8.1;
Variant Encumbrance+Midi v 0.4.6;
Vehicles and Mechanisms v 0.4.0;
Wall Height v 3.5.3.9;
Your Tokens Visible v 2.7.0;

**Comment by manuelVo** [comment]
Please export the bugged scene and upload it here. That'll help me find and fix the bug.

**Comment by ariakas2008** [comment]
[fvtt-Scene-(s)-l4_-chamber-of-horrors.zip](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/7198683/fvtt-Scene-.s.-l4_-chamber-of-horrors.zip)
here it is. Thank you.

**Comment by manuelVo** [comment]
Debug data for the bug:
```
<~"*iOjRt$6!eJ6,KLKHlW+f%CjRm6g<MNh"BBgk?:#I.uV6]kE,PZ"tgg-rJKMMMtG>7'[pUI6o>1UGcVm*'f4DeHD_mqneTLd[4H+qdr\OW]SWLO](hclbV!rlBKU):$o\k8s:,+5c2Oah@/gHZ/=8n'8kijH]B,m)57jdG0c@nZdhiPEV2;r;XM&Qc$aS3,ZPlYKj[8@,-&r;jcupR?kTD4LT`tr!DqYX\"KBO-.&_-8EXb8'YpF@[t%Pf\5ouUZ)XAhjBkLW-AdI-<lZN'sA+.]q=#I`2Inlq4+QYN/GNj@s5rE,Y#b-:YS\a3h;ga%E\1BatNUu(Qfg/Bb)U$kLuPN%7rd+o(Cs]j_A"`)!;Re>oGCH[NU.Leg*`\F(kMqq[S])jg`K8Ao(1NP^ga(8VPRMI[?oc)W66Mq6$hkN7N13F1g8W'LllME7O;qC!5*<NsY6dAc(mjhSa:-:RSOLQNiEALo)lkh1b$(e^c!89,Q?*c.#o5"@fM-T/Ji=9D5nQ@+<%>SUB>G,Y%0J>aiO.rT*J#feBfD*X4&GXu;l@l*'I),Y%0"aOf.7`2NVG3do-$,W7^8[sUOu`2NKb92c\jFNUE\UIBS.l#!;p0[@dCQNiD/h<WK'`]=!]9*7Wkf=Qc*@@SR5<#@K1EbPlU`^*ZR'h7k5Y0TgN<6*U#nqsP@N99Zc9O9V7L!ffF0"QCH9k%'4fBTHn8Vp:RpY@Q.;]%[oSkE!!4o.?gnL[t/(bJF<&MCc,,fVjm8VQ\7F6o"SiW@-OBQMIA.0JTlU3Xh&irJ+uLIFlEc]iCX0@%'K$G\Vk/hVj_*mk\AH1<O?%2^ru\;!C[S0OS((f(/VR_h$;q6VjQ$.GB"(@Z;01m.fTC's"6E/R?k`Y4B"G4g)sER(B]ius7m$KE,jUr)?j&S-7EXYA&NQ:h>"X]H0;-\5,&[=sBbChjZYmRJm(@FVuHf'Sa,_PiBu9@[>R.#bI&/kocElT8>i0Q'&E7AV^'@qb0$qFtCgCO9;)0Nr?=ml!%WEK4:f$DWm@>aiMhf<0..^o5$,dM0^3EPSCOU[1V6S*d7E@[,jC>DQr*j#\IU#Z;L^_ir;NdOL1ge0c("cV7i4@*Q%I7pD/o-2W,EI\e',I8MGPCCCeL@FW2P\9Z`X,Y"j0HXql/0O!;plD2:1Xm=EdZLM+/?D9,'AmLkBW;$n+)LKc+0O"K&ns$+&N,rKa9*7X2T5\KOiuC'<L!cn"+koq3KlLE[m*^F3a\sfd@<D(FiN_uA>E]o++*;3(U\.uhFo00U(gh)Ps*%b4^c8g#?!<V1kL2%X@@SPuo.A['E?j:LCDW6/+gejtm8eTNHm!LBmF$O4.MgHLHQ&n<c6s[Q1p/M#G%h;Y%'uYo&R1G9QeJbjp2a,@UR_-:4InjY^1Z%F'h3gP429(j'ZR\1ZV(Biq6uK9DdOe'UE"%iX:IqLmH;CI$DoUpB9;N3'LqomL<%#6<DsarGVR\EYH:BT>OPm=FV5OnmIb1?Q1d%<T=6\7dFr<)lPWojR/T?CLBK7^HDo?V4crCFhKUV6m*^E(lS7f#nQN#XG79PU(stGZ\Q$b:L/.K8G+Di%BJVhh7VR(V3a)AKhDiL3OmRpU_Pm5I>(=ZF,XqrD"82$$X2;C>hD\]1"?-*h[ej7G2c&'cdYh@8''%bs`MEUa+%Y`[5_!o-mgNC=Ra?Q'l-',@_kXQbY!KM>d0epH0]UT3d>@A@koZe"0KOcBmnrrsM8Es!U?gUO/!<?&9gbV(Zrj;01V?P2ohGoKI4^F[LI(g,egfgX(Xp^i^>X)(p7YA%[h>iOBXWuHYu3t<O7i4(*%Nkk6dMnJ\[70MP2AAck"m'eNbS0%UkW.N"rcY=lH18?ME32pC4n?8aH=%h=*eN&cE1Pio<4LOS#M)XTj)<p'i3)%l]>)IOXu!A0NLitV8a`oCC9*;1nnh9`a'9G'[soiL)g$E'K2tb-h[f7NdN7.gcB4X>S<h**g``XcEUGT@?Y=uk0AFB#)lcEBF<c>fb^GkUoBJ.qZ)qBW,oSD>8sdE955W2>+;Tq]9(lKH(Wbn=F_D^i@;aQGs!0`QiB9^!A-%K_L6[Eeg*^82^%!kC2L<j[M*d[ge$k#64FkD>+!"Sd;$iWU=O5cL0_6q9paG$!f!gTc-nlDN7,R-F2+j9S2q,TcZGbd[ASQ"bLS^-fHYZ:[T:Eu^LOH.lMG+-[I_K5g9ci;HSsSDGhZPQhq%Y>0F_l/VH:0<$7WDBLR3\Y[&^U=+"4L^@QIFNDg)gU)B5AD2F+^[2hW?Qj4W<ZJ\PVp%+?<?el&T&)q1s2X(+2Z?K]bd<^_D\G3fs/_Pm&YN_N`A(aVBXIkQ4c,V_oqSA<mT;GCVqUKsKk(aZ+^VDm.r`:t<NHO$gmoVPFY0.l$G[U5.FN:OIJ7:kpU<>ahe5&F54@B"@kf(=hLjE4[jAPC7Of^.>8#DH$HC2Nl`0i_DU+PKUDr\X`u#/t:eqgF"3W5,E_q%'n\0e2\R>/&kE,W<fWHl?b_"^XB(p((pQ7`@1)G,\bUUL0;=PMQ=HPD@#q!)MjS&PZ^k#TJ4>Ce\@q^r*g"n+]]r%EPH0de<Gs\OUcT`IXe-KjJ2pH:a'3Cu$,?'8;C;R$GrE,t@-r92c\jYihuR;j1Hi_8mrBVP\j9Z#lnbV2LU#a(tWp/e&Z,*mk\AHg)b>5,mKk,Q))H5pB*"P\c\_nQI;aBu%5N'@F\^5-u)k8<HXsN&-JK/K>REEG<(LEE\rLW:WQ66u.q9'ZQbT6rOrcYb[7liO_/cjW^/13/;X#6jr>Kd!A)YR(fq#[*)#>$Sa41pHPG5-b!B$i6tn[8%\<c]4V:Kq&H8L[SH~>
```

**Comment by manuelVo** [comment]
Minimal testcase:
```
<~"*iOJNBIb:5S/W^\V*Ed:>c=T8/suR_?GV8?9k>WV6prj3/(#h`<H2,7'b(O@_TLAH$KBtiAAD%m'u'!2:!+dDLHm:/g?t0'F1@'WE,I&l8<DUeNU6FEd.-/5>PrqmVu&l&fo+&%[q8uarcZ~>
```

**Comment by manuelVo** [comment]
This bug is fixed in the next release of Lichtgeschwindigkeit (1.4.6).

Here's some advice on how to optimize your maps for performance, though:
As you can see in this debugging-screenshot the end point (blue) of the vertical wall on the right is slightly above the horizontal wall at the top. This causes these walls to intersect (the intersection point is red). Intersection points are bad for performance, because the algorithm has to split each intersecting wall in half. So for each two walls that intersect the algorithm actually needs to calculate four walls instead of two. To avoid this issue, try to snap wall endpoints to grid (or the subgrid) whenever possible. If the walls touch, but don't intersect they will block all vision (no gap will remain on the touching point), while the performance penalty is avoided.

**Comment by ariakas2008** [comment]
> This bug is fixed in the next release of Lichtgeschwindigkeit (1.4.6).
> 
> Here's some advice on how to optimize your maps for performance, though:
> As you can see in this debugging-screenshot the end point (blue) of the vertical wall on the right is slightly above the horizontal wall at the top. This causes these walls to intersect (the intersection point is red). Intersection points are bad for performance, because the algorithm has to split each intersecting wall in half. So for each two walls that intersect the algorithm actually needs to calculate four walls instead of two. To avoid this issue, try to snap wall endpoints to grid (or the subgrid) whenever possible. If the walls touch, but don't intersect they will block all vision (no gap will remain on the touching point), while the performance penalty is avoided.

Ok thank you. Can't see the debugging-screenshot here, though....

**Comment by manuelVo** [comment]
Oops, forgot to include it... Here you go
![grafik](https://user-images.githubusercontent.com/1705157/134139920-5740723a-6340-4d16-ad50-bb5dd2d8b8c3.png)

**Comment by ariakas2008** [comment]
Thanks. Is there a way to easily highlight-debug all of those intersections in the whole scene, as you did with the red one in the screenshot? Since I didn't do the walling for my world (r20 conversion) I could easily miss lots of them.

**Comment by manuelVo** [comment]
You can press F12 to open the js console and enter `CONFIG.debug.sightRays = true;` and press enter. Then select a token. That'll show the debug screen. All intersections will be marked with a red dot. To get rid of the debug data simply reload foundry.

If you're having a lot of maps that you want to optimize, that would probably best be done with a script tough.
