### ISSUE TITLE
Why obfuscate? 

### ISSUE THREAD

**Issue by crnormand** [manuelVo/foundryvtt-lichtgeschwindigkeit#3]
I am just wondering why you have obfuscated your code, when everything else is open source.   Do you plan to sell this module?

**Comment by manuelVo** [comment]
The module isn't obfuscated. It uses a technology called "WebAssembly", which allows to write faster programs than is possible using javascript. On part of the performance improvement WebAssembly provides is stems from the fact that WebAssembly is extremely close to the actual instructions that your computer will be executing. This keeps translation overhead from webassembly to computer instructions at a miniumum. However this also causes WebAssembly to be a binary blob that's quite unreadable for humans (there's a "human readable" presentation that your browsers debugger can show you, but you'll find it's nothing like Javascript to read).

However you're right about the fact that the source code that I've used to compile currently isn't available to the public. The reason for this is that I'm completely undecided on the future of this module. Could be that I decide to sell it in the future. Currently I'm holding that avenue open for myself by not publishing the source, while still allowing interested people to use it for free for the time being. But it might as well be that I'll publish the source code on Github in a few weeks. Only time can tell.

**Comment by crnormand** [comment]
Understood... and thanks.   I saw the reference to the 64 bit memory blob... a trick that I have used in Java VMs (to get around Java's painfully slow object referencing mechanism)... and I was wondering if it was like that.   I googled WebAssembly and found their webpage... very interesting.

Well, good luck!

**Comment by manuelVo** [comment]
Good news: I've just published the full source code of this module on Github!
