### ISSUE TITLE
Light leak with limited sight angle bug still persists in 1.4.7

### ISSUE THREAD

**Issue by Cerapter** [manuelVo/foundryvtt-lichtgeschwindigkeit#31]
Similar to the issues #25 and #29, may be fixed by #30 already, thought I'd report it anyway.

The setup:
![licht_bug_setup](https://user-images.githubusercontent.com/43446478/134810438-b76708e7-5d69-4107-b2e1-2c6183be130e.png)

In action:
![licht_bug_in_action](https://user-images.githubusercontent.com/43446478/134810437-8c6a282d-6157-4b4b-9c99-66cc6b0395ba.png)

With `CONFIG.debug.sightRays = true;`:
![licht_bug_debug](https://user-images.githubusercontent.com/43446478/134810434-104786f7-6dbc-4c06-985c-33d10ac615b8.png)

Debug data:
```
<~"*iObN@P?d5S/Z_nI?c0+j@Bo@^-:"%0UTW'eBP2?rR]L+<F#e]@#bN>o1H=raA")i?&7('W`OhJuO1inKM?dKUai'RD@,DW<k3kWO&K#o8Qa"G8]D"@Rfr\++:CQ3BPc[Hc&./]*IdE==P]G~>
```

**Comment by manuelVo** [comment]
This doesn't look similar to #30, probably a new bug. Thanks for the report!

**Comment by manuelVo** [comment]
Very well reduced debug data. This was very easy to debug and fix. Thanks for that as well.

**Comment by Cerapter** [comment]
Bug persists still, but in the opposite direction.

Setup:
![licht_bug_2_setup](https://user-images.githubusercontent.com/43446478/135135362-11f21b07-1baa-46d4-ad8c-a166f9504082.png)

In action:
![licht_bug_2_in_action](https://user-images.githubusercontent.com/43446478/135135360-f15d57d3-a7e2-4590-82ea-09392b284b18.png)

With `CONFIG.debug.sightRays = true;`:
![licht_bug_2_debug](https://user-images.githubusercontent.com/43446478/135135355-46d9fc97-82e7-463d-833f-c68633413210.png)

Debug data:
```
<~"*iOZM`hP85S/W^--ecM:cj6V,V#-WlCEH3UD=$(XXG2U6K&RR/[t>X4#ECs@_VXbmf@rmI">q7Q^Y*:[3B,IhM"c--h/"jBeu`faNtuL,sCV]20VI`r=e23rHOA)FNIHj<pJ]H:<XlS~>
```

**Comment by manuelVo** [comment]
It might not seem like it, but it's a different bug than the one you originally reported. I've filed it as #32.
