### ISSUE TITLE
Directional Walls Issues

### ISSUE THREAD

**Issue by RandomLegend** [manuelVo/foundryvtt-lichtgeschwindigkeit#4]
Hello,

first of all: fundamentally - Great module! Works like a charm...as long as it doesnt :-D
I face problems with one sided walls:
![grafik](https://user-images.githubusercontent.com/38812603/122598027-8b79e900-d06c-11eb-8839-87b54e3b99cf.png)

This is the current Wall configuration.
![grafik](https://user-images.githubusercontent.com/38812603/122598152-be23e180-d06c-11eb-961d-1a50b731d736.png)

And this is how its supposed to look like (as you can already see from the configuration. This picture is with the core lighting calculation:
![grafik](https://user-images.githubusercontent.com/38812603/122598327-f9261500-d06c-11eb-8f8b-4708ea826f5d.png)

I already deactivated every single module but Lichtgeschwindigkeit and the issue persists.
I am using foundry 0.8.7

**Comment by manuelVo** [comment]
Hello. Thanks for the report. To help me easily debug and fix this, please do the following:

 - Open the Javascript console (press F12 to do so)
- Type `CONFIG.debug.sightRays = true` into the console.

Now every time you move the token, some garbled text should appear in the console. Move the token into a position that triggers the bug and send me the last text that is written into the console (it may seem random, but it contains information that's ver helpful for me to debug the issue).

**Comment by RandomLegend** [comment]
Hey,

i hope i did it correctly.
___________________________________________________________________________________________________________________________
<~!-m47P.PH1;%SJCH%K#3+sBY^H%\G?r2&ZK!%CekTUh?M$=6h'h=Z@JMn#U[V1k`V+BE[^!#Cld?=n<?f>GJOI!dJdAr^s#!Te6D3%/YiWsPnJbh2o)#(Ie!#g=HH``b.422<%&ENO<E&4>V^l\%::clHnm1kupbH`]6h&4?Ifmr6Z10ap1d;V)mtLo-?lb+,d2;]TRAP-s8j\RUBP;6lcLLDZI5\s#'oLnUsBncNrhTqhS^,BJ[7Vn;K*jq'nIf)A_4&49h)=.>UF%"jD^$0Dd\cae(9GFJI>-[,1FBf@f>@HqS#gk(laImfp4.-`t5^]1KKr#JZrA7Q4KZNHP?K5L~>
___________________________________________________________________________________________________________________________

i hope this is helpful.
Btw: I just found a spot where it now blocks any vision too...There are no walls or something there so this is bugged too.
___________________________________________________________________________________________________________________________
<~!-m47P.aTl;%SF75(StR;.HAXmpP*'.=D1($Oc@'N9)CD!VtCP2Im+*[\P1q:f-]_)_0!Y!")=jIV*!/JX]A/k0'*\\MNQA]0P?.D%:Roa\l/TCbrEsR),CdrW_Kr6Zk$WZS[FS_Fq!oF,6O[Wccl4@YdKW^RIS!X`LT\jq'oC7Gi(21GO"CP(/TS`"5]io;O_RmAJIcN$ZZ\STDdZ_6mgm1PZf^GIitCF,2!hH23"O`6cm1r4Y20d+$nHhrYJ;lVm[Rboqh%hH*Ir+boDek6,j^mH=Csn919!#q'fdcdQd?pI+8d9laH.0pt5F:\Vrp458WBgE7J&8r#(Q_sXT+a2iqQ~>
___________________________________________________________________________________________________________________________

This is the snipped for that position

**Comment by manuelVo** [comment]
Yes, that's exactly what I needed, thanks. A tip for the next time; If you put such data into three backticks like this:

````
```
<~!-m47P.aTl;%SF75(StR;.HAXmpP*~>
```
````

Github will render it into a neat grey box and will refrain from interpreting the contained data in any weird way (like it interpreted the `~` as a signal to strike through the text).
