### ISSUE TITLE
Scene breaks after name change v1.1.1

### ISSUE THREAD

**Issue by Mad-Jackalope** [manuelVo/foundryvtt-lichtgeschwindigkeit#7]
I had  a scene with some lights and changed its name and the global illumination to off.
That made foundry unable to load the canvas.

I was able to open the map as soon as I disabled Lichtgeschwindigkeit. After I deleted all the lights on the scene and turned it on again it worked fine.

vtt 0.8.7
Pathfinder2 2.4.0.6221
Lichtgeschwindigkeit 1.1.1

**Comment by manuelVo** [comment]
Please check if there are any errors in the javascript console (press f12 to open the console) when the scene fails to load. If so, please attach the error message and debugging data to this issue.

**Comment by manuelVo** [comment]
This is possibly the same bug as #10, but to verify this I'll need the debugging data.

**Comment by manuelVo** [comment]
Since a lot of similar issues have been fixed since this issue has been reported and there is no feedback from the issue author I'm assuming this issue is resolved. Should the issue persist feel free to reopen this issue.
